# Generated by Django 4.2.7 on 2023-11-13 19:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patient",
            old_name="patient_birth_date",
            new_name="birth_date",
        ),
        migrations.RenameField(
            model_name="patient",
            old_name="patient_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="patient",
            old_name="patient_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="patient",
            old_name="patient_sex",
            new_name="sex",
        ),
        migrations.RenameField(
            model_name="patient",
            old_name="patient_surname",
            new_name="surname",
        ),
        migrations.RenameField(
            model_name="test",
            old_name="test_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="test",
            old_name="test_reference",
            new_name="reference",
        ),
    ]
